# Generated by Django 5.0 on 2024-01-10 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('figura', models.ImageField(upload_to='img')),
                ('nome_do_curso', models.CharField(max_length=100, unique=True)),
                ('perfil_de_entrada', models.TextField()),
                ('perfil_de_saida', models.TextField()),
                ('duracao', models.CharField(max_length=10, verbose_name='Duração')),
                ('total_disc', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Provincias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provincia', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='img', verbose_name='Foto Tipo Passe')),
                ('arquivo', models.FileField(upload_to='pdf', verbose_name='Bilhete de Identidade (Anexo)')),
                ('nAgente', models.CharField(max_length=9, unique=True, verbose_name='Número de Agente')),
                ('nome_completo', models.CharField(max_length=150)),
                ('estado_civil', models.CharField(choices=[('Solteiro(a)', 'Solteiro(a)'), ('Casado(a)', 'Casado(a)'), ('Divorcio(a)', 'Divorcio(a)')], max_length=50)),
                ('numero_do_bilhete', models.CharField(max_length=14, unique=True, verbose_name='Número do Bilhete')),
                ('data_de_emissao', models.DateField()),
                ('data_de_nascimento', models.DateField()),
                ('local_de_nascimento', models.CharField(max_length=50)),
                ('municipio', models.CharField(max_length=100, verbose_name='Município')),
                ('provincia', models.CharField(max_length=100, verbose_name='Província')),
                ('residencia', models.CharField(max_length=100, verbose_name='Residência')),
                ('contacto', models.CharField(max_length=18, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nivel_academico', models.CharField(choices=[('Técnico Médio', 'Técnico Médio'), ('Licenciado(a)', 'Licenciado(a)'), ('Mestre', 'Mestre'), ('Phd', 'Phd')], max_length=100)),
                ('especialidade', models.CharField(max_length=100)),
                ('instituicao', models.CharField(max_length=100, verbose_name='Instituição de formação')),
                ('data_de_ingresso', models.DateField()),
                ('categoria', models.CharField(choices=[('Prof. Do Ens. Prim. E Sec. Do 3.º Grau', 'Professor Do Ens. Prim. E Sec. Do 3º Grau'), ('Professor Do Ens. Prim. E Sec. Do 12º Grau', 'Professor Do Ens. Prim. E Sec. Do 12º Grau'), ('Prof. Do Ens. Prim. E Sec. Do 5.º Grau', 'Professor Do Ens. Prim. E Sec. Do 5º Grau'), ('Professor Auxiliar Do 4º Grau', 'Professor Auxiliar Do 4º Grau'), ('Prof. Do Ens. Prim. E Sec. Do 9.º Grau', 'Professor Do Ens. Prim. E Sec. Do 9º Grau'), ('Professor Auxiliar Do 5º Grau', 'Professor Auxiliar Do 5º Grau'), ('Professor Do Ens. Prim. E Sec. Do 11º Grau', 'Professor Do Ens. Prim. E Sec. Do 11º Grau'), ('Professor Do Ens. Prim. E Sec. Do 13º Grau', 'Professor Do Ens. Prim. E Sec. Do 13º Grau'), ('Prof. Do Ens. Prim. E Sec. Do 1.º Grau', 'Professor Do Ens. Prim. E Sec. Do 1º Grau'), ('Professor Auxiliar Do 2º Grau', 'Professor Auxiliar Do 2º Grau'), ('Prof. Do Ens. Prim. E Sec. Do 2.º Grau', 'Professor Do Ens. Prim. E Sec. Do 2º Grau'), ('Prof. Do Ens. Prim. E Sec. Do 6.º Grau', 'Professor Do Ens. Prim. E Sec. Do 6º Grau'), ('Prof. Do Ens. Prim. E Sec. Do 7.º Grau', 'Professor Do Ens. Prim. E Sec. Do 7º Grau'), ('Professor Auxiliar Do 1º Grau', 'Professor Auxiliar Do 1º Grau'), ('Professor Auxiliar Do 3º Grau', 'Professor Auxiliar Do 3º Grau'), ('Prof. Do Ens. Prim. E Sec. Do 8.º Grau', 'Professor Do Ens. Prim. E Sec. Do 8º Grau'), ('Prof. Do Ens. Prim. E Sec. Do 4.º Grau', 'Professor Do Ens. Prim. E Sec. Do 4º Grau'), ('Professor Do Ens. Prim. E Sec. Do 10º Grau', 'Professor Do Ens. Prim. E Sec. Do 10º Grau'), ('Professor Auxiliar Do 6º Grau', 'Professor Auxiliar Do 6º Grau')], max_length=150)),
                ('funcao', models.CharField(choices=[('Subdirector Pedagógico', 'Subdirector Pedagógico'), ('Funcionário(a) Auxiliar', 'Funcionário(a) Auxiliar'), ('Chefe da Secretaria Pedagógica', 'Chefe da Secretaria Pedagógica'), ('Chefe da Secretaria Geral', 'Chefe da Secretaria Geral'), ('Funcionário(a) Administrativo(a)', 'Funcionário(a) Administrativo(a)'), ('Subdirector Administrativo', 'Subdirector Administrativo'), ('Director', 'Director'), ('Coordenador(a) de Disciplina', 'Coordenador(a) de Disciplina'), ('Coordenador(a) do Curso', 'Coordenador(a) do Curso'), ('Professor(a)', 'Professor(a)')], max_length=32, verbose_name='Função')),
                ('disciplina', models.CharField(max_length=300, null=True, verbose_name='Disciplina ou Curso')),
                ('dados_academicos', models.TextField()),
                ('dados_profissionais', models.TextField()),
                ('utilizador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img', verbose_name='Fotografia')),
                ('painel', models.CharField(choices=[('Principal', 'Principal'), ('Acima', 'Acima'), ('Abaixo', 'Abaixo')], max_length=20)),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('figura', models.ImageField(upload_to='img')),
                ('titulo', models.CharField(max_length=500, unique=True)),
                ('texto', models.TextField()),
                ('data', models.DateTimeField(auto_now=True)),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Municipios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.CharField(max_length=100, unique=True)),
                ('Provincia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestao.provincias')),
            ],
        ),
        migrations.CreateModel(
            name='quadro_de_honra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img', verbose_name='Fotografia do aluno')),
                ('nome_do_aluno', models.CharField(choices=[('Principal', 'Principal'), ('Acima', 'Acima'), ('Abaixo', 'Abaixo')], max_length=20)),
                ('classe', models.CharField(max_length=20, verbose_name='Classe que frequenta')),
                ('referencia', models.CharField(choices=[('Iº Trimestre', 'Iº Trimestre'), ('IIº Trimestre', 'IIº Trimestre'), ('IIIº Trimestre', 'IIIº Trimestre'), ('Anual', 'Anual')], max_length=20, verbose_name='Referência da avaliação')),
                ('desc_notas', models.TextField(verbose_name='Descrição das notas')),
                ('media_obtida', models.IntegerField(verbose_name='Média Obtida')),
                ('data', models.DateTimeField(auto_now=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.cursos', verbose_name='Curso que frequenta')),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
